apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sample-api
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/swathymaya94/Intuitive.Ai-Platform-Assessment.git
    targetRevision: feat/argocd-bootstrap
    path: applications/sample-api/base

  destination:
    server: https://kubernetes.default.svc
    namespace: sample-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
